ALTER TABLE "gear_catalog_items" ADD COLUMN "key" varchar(128);--> statement-breakpoint
UPDATE "gear_catalog_items"
SET "key" = CASE "name"
  WHEN 'намет' THEN 'tent'
  WHEN 'футпринт' THEN 'footprint'
  WHEN 'спальник' THEN 'sleeping_bag'
  WHEN 'килимок' THEN 'sleeping_pad'
  WHEN 'надувачка для килимка' THEN 'sleeping_pad_pump'
  WHEN 'ремкомплект для килимка' THEN 'sleeping_pad_repair_kit'
  WHEN 'джерело вогню' THEN 'fire_source'
  WHEN 'резервне джерело вогню' THEN 'backup_fire_source'
  WHEN 'ложка' THEN 'spoon'
  WHEN 'тарілка' THEN 'plate'
  WHEN 'горнятко' THEN 'mug'
  WHEN 'ніж' THEN 'knife'
  WHEN 'ємності для води' THEN 'water_containers'
  WHEN 'фільтр для води' THEN 'water_filter'
  WHEN 'інгетрована система' THEN 'integrated_stove_system'
  WHEN 'газовий балон' THEN 'gas_canister'
  WHEN 'косметичка' THEN 'toiletry_bag'
  WHEN 'рушник' THEN 'towel'
  WHEN 'сонцезахисний крем' THEN 'sunscreen'
  WHEN 'сонцезахисна помада' THEN 'lip_sunscreen'
  WHEN 'зволожуючий крем' THEN 'moisturizer'
  WHEN 'зубна паста' THEN 'toothpaste'
  WHEN 'зубна щітка' THEN 'toothbrush'
  WHEN 'лопатка для туалету' THEN 'toilet_trowel'
  WHEN 'туалетний папір' THEN 'toilet_paper'
  WHEN 'мило' THEN 'soap'
  WHEN 'міні-ножиці' THEN 'mini_scissors'
  WHEN 'люстерко' THEN 'mirror'
  WHEN 'рюкзак' THEN 'backpack'
  WHEN 'рейнкавер' THEN 'rain_cover'
  WHEN 'трекінгові палички' THEN 'trekking_poles'
  WHEN 'ліхтарик' THEN 'flashlight'
  WHEN 'гермомішки' THEN 'dry_bags'
  WHEN 'сонцезахисні окуляри' THEN 'sunglasses'
  WHEN 'москітка сітка' THEN 'mosquito_net'
  WHEN 'апка з картами' THEN 'maps_app'
  WHEN 'завантажити офлайн карти' THEN 'offline_maps'
  WHEN 'карта ламінована' THEN 'laminated_map'
  WHEN 'компас' THEN 'compass'
  WHEN 'телефон' THEN 'phone'
  WHEN 'павербанк' THEN 'power_bank'
  WHEN 'шнури' THEN 'cables'
  WHEN 'гермомішок для електроніки' THEN 'electronics_dry_bag'
  WHEN 'фотоапарат' THEN 'camera'
  WHEN 'карти памяті' THEN 'memory_cards'
  WHEN 'паспорт' THEN 'passport'
  WHEN 'готівка' THEN 'cash'
  WHEN 'банківська карта' THEN 'bank_card'
  WHEN 'дозвіл від прикордонників' THEN 'border_guard_permit'
  WHEN 'водонепроникний чохол' THEN 'waterproof_case'
  WHEN 'ремнабір' THEN 'repair_kit'
  WHEN 'пакет для сміття' THEN 'trash_bag'
  WHEN 'сідачка' THEN 'sit_pad'
  WHEN 'міні-гамак' THEN 'mini_hammock'
  WHEN 'шкарпетки трекінгові' THEN 'trekking_socks'
  WHEN 'футболка трекінгова' THEN 'trekking_tshirt'
  WHEN 'штани трекінгові' THEN 'trekking_pants'
  WHEN 'шорти' THEN 'shorts'
  WHEN 'фліска' THEN 'fleece_jacket'
  WHEN 'флісові штани' THEN 'fleece_pants'
  WHEN 'пуховка' THEN 'down_jacket'
  WHEN 'вітрівка' THEN 'windbreaker'
  WHEN 'мембранка' THEN 'membrane_jacket'
  WHEN 'баф' THEN 'buff'
  WHEN 'панама' THEN 'sun_hat'
  WHEN 'шапка' THEN 'beanie'
  WHEN 'рукавиці' THEN 'gloves'
  WHEN 'взуття' THEN 'footwear'
  WHEN 'тапки' THEN 'camp_shoes'
  WHEN 'знежарювальне' THEN 'fever_reducer'
  WHEN 'обезболююче' THEN 'painkiller'
  WHEN 'пластир' THEN 'adhesive_bandages'
  WHEN 'чай' THEN 'tea'
  WHEN 'кава' THEN 'coffee'
  WHEN 'спеції' THEN 'spices'
  WHEN 'батончики' THEN 'bars'
  WHEN 'сублімована їжа' THEN 'freeze_dried_food'
END;--> statement-breakpoint
ALTER TABLE "gear_catalog_items" ALTER COLUMN "key" SET NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "gear_catalog_items_category_key_unique" ON "gear_catalog_items" USING btree ("category_id","key");--> statement-breakpoint
ALTER TABLE "gear_catalog_items" DROP COLUMN "name";
